DROP TABLE IF EXISTS urls CASCADE;
CREATE TABLE urls(
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255),
    created_at date
    );

DROP TABLE IF EXISTS url_checks CASCADE;
create table url_checks(
	id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	url_id bigint references urls(id),
	status_code int,
	h1 varchar(255),
	title varchar(255),
	description varchar(255),
	created_at date
);